import { staticServer } from "../serverUrl"

export const skin = [
    {
        id: 0,
        name: 'Classic',
        name_ko: '클래식',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '아발란체',
                category: 'avalanche',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '파이널 챔버',
                category: 'sages',
                level: 0,
                cost: '세이지 계약',
            },
            {
                id: 2,
                name_ko: '임페리엄',
                category: 'imperium',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 3,
                name_ko: '피스톨',
                category: 'razes',
                level: 0,
                cost: '레이즈 계약',
            },
            {
                id: 4,
                name_ko: '갤러리아',
                category: 'galleria',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 5,
                name_ko: '킹덤',
                category: 'kingdom',
                level: 0,
                cost: '배틀패스 액트1',
            },
            {
                id: 6,
                name_ko: '프라임 1',
                category: 'prime',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 7,
                name_ko: '프라임 2',
                category: 'prime',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 8,
                name_ko: '프라임 3',
                category: 'prime',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 9,
                name_ko: '프라임 4',
                category: 'prime',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 10,
                name_ko: '벚꽃',
                category: 'sakura',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 11,
                name_ko: '적색경보',
                category: 'redalert',
                level: 0,
                cost: '배틀패스 액트2 티어40',
            },
            {
                id: 12,
                name_ko: '스플라인 1',
                category: 'spline',
                level: 1,
                cost: '미정',
            },
            {
                id: 13,
                name_ko: '스플라인 2',
                category: 'spline',
                level: 2,
                cost: '미정',
            },
            {
                id: 14,
                name_ko: '스플라인 3',
                category: 'spline',
                level: 3,
                cost: '미정',
            },
            {
                id: 15,
                name_ko: '스플라인 4',
                category: 'spline',
                level: 4,
                cost: '미정',
            },
        ]
    },
    {
        id: 1,
        name: 'Shorty',
        name_ko: '쇼티',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '스네이크 바이트',
                category: 'vipers',
                level: 0,
                cost: '바이퍼 계약',
            },
            {
                id: 1,
                name_ko: '도깨비 1',
                category: 'oni',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 2,
                name_ko: '도깨비 2',
                category: 'oni',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 3,
                name_ko: '도깨비 3',
                category: 'oni',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 4,
                name_ko: '도깨비 4',
                category: 'oni',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 5,
                name_ko: '천재 요원',
                category: 'killjoys',
                level: 0,
                cost: '킬조이 계약',
            },
        ]
    },
    {
        id: 2,
        name: 'Frenzy',
        name_ko: '프렌지',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '라그나록커',
                category: 'breachs',
                level: 0,
                cost: '브리치 계약',
            },
            {
                id: 1,
                name_ko: '스핏파이어',
                category: 'phoenixs',
                level: 0,
                cost: '피닉스 계약',
            },
            {
                id: 2,
                name_ko: '러쉬',
                category: 'rush',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 3,
                name_ko: '쿠튀르',
                category: 'couture',
                level: 0,
                cost: '배틀패스 액트1 티어16',
            },
            {
                id: 4,
                name_ko: '엘더플레임 1',
                category: 'elderflame',
                level: 1,
                cost: '2475 VP',
            },
            {
                id: 5,
                name_ko: '엘더플레임 2',
                category: 'elderflame',
                level: 2,
                cost: '2475 VP',
            },
            {
                id: 6,
                name_ko: '엘더플레임 3',
                category: 'elderflame',
                level: 3,
                cost: '2475 VP',
            },
            {
                id: 7,
                name_ko: '엘더플레임 4',
                category: 'elderflame',
                level: 4,
                cost: '2475 VP',
            },
            {
                id: 8,
                name_ko: '글리치팝 1',
                category: 'glitchpop',
                level: 1,
                cost: '2175 VP',
            },
            {
                id: 9,
                name_ko: '글리치팝 2',
                category: 'glitchpop',
                level: 2,
                cost: '2175 VP',
            },
            {
                id: 10,
                name_ko: '글리치팝 3',
                category: 'glitchpop',
                level: 3,
                cost: '2175 VP',
            },
            {
                id: 11,
                name_ko: '글리치팝 4',
                category: 'glitchpop',
                level: 4,
                cost: '2175 VP',
            },
        ]
    },
    {
        id: 3,
        name: 'Ghost',
        name_ko: '고스트',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '소울 사일런서',
                category: 'omens',
                level: 0,
                cost: '오멘 계약',
            },
            {
                id: 1,
                name_ko: '허쉬',
                category: 'cyphers',
                level: 0,
                cost: '사이퍼 계약',
            },
            {
                id: 2,
                name_ko: '럭스',
                category: 'luxe',
                level: 0,
                cost: '875 VP',
            },
            // {
            //     id: 3,
            //     name_ko: '럭스 레벨2',
            //     category: 'luxe',
            //     level: 2,
            //     cost: '875 VP',
            // },
            // {
            //     id: 4,
            //     name_ko: '럭스 레벨3',
            //     category: 'luxe',
            //     level: 3,
            //     cost: '875 VP',
            // },
            // {
            //     id: 5,
            //     name_ko: '럭스 레벨4',
            //     category: 'luxe',
            //     level: 4,
            //     cost: '875 VP',
            // },
            {
                id: 6,
                name_ko: '프리즘',
                category: 'prism',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 7,
                name_ko: '벤데타',
                category: 'reynas',
                level: 0,
                cost: '레이나 계약',
            },
            {
                id: 8,
                name_ko: 'DOT EXE',
                category: 'dotexe',
                level: 0,
                cost: '배틀패스 액트1 티어35',
            },
            {
                id: 9,
                name_ko: '소버린 1',
                category: 'sovereign',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 10,
                name_ko: '소버린 2',
                category: 'sovereign',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 11,
                name_ko: '소버린 3',
                category: 'sovereign',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 12,
                name_ko: '소버린 4',
                category: 'sovereign',
                level: 4,
                cost: '1775 VP',
            },
        ]
    },
    {
        id: 4,
        name: 'Sheriff',
        name_ko: '셰리프',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '피스키퍼',
                category: 'brimstones',
                level: 0,
                cost: '브림스톤 계약',
            },
            {
                id: 1,
                name_ko: '게임 오버',
                category: 'jetts',
                level: 0,
                cost: '제트 계약',
            },
            {
                id: 2,
                name_ko: '프로텍터',
                category: 'sovas',
                level: 0,
                cost: '소바 계약',
            },
            {
                id: 3,
                name_ko: '약탈자',
                category: 'reaver',
                level: 0,
                cost: '1775 VP',
            },
            {
                id: 4,
                name_ko: '무사',
                category: 'ronin',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 5,
                name_ko: '아리스토크랫',
                category: 'aristocrat',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 6,
                name_ko: '콘벡스',
                category: 'convex',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 7,
                name_ko: '벚꽃',
                category: 'sakura',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 8,
                name_ko: '폴리폭스',
                category: 'polyfox',
                level: 0,
                cost: '배틀패스 액트2 티어16',
            },
            {
                id: 9,
                name_ko: '네뷸라',
                category: 'nebula',
                level: 0,
                cost: '1775 VP',
            },
        ]
    },
    {
        id: 5,
        name: 'Stinger',
        name_ko: '스팅어',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '아리스토크랫',
                category: 'aristocrat',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '쿠튀르',
                category: 'couture',
                level: 0,
                cost: '배틀패스 액트1 티어15',
            },
            {
                id: 2,
                name_ko: '소버린 1',
                category: 'sovereign',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 3,
                name_ko: '소버린 2',
                category: 'sovereign',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 4,
                name_ko: '소버린 3',
                category: 'sovereign',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 5,
                name_ko: '소버린 4',
                category: 'sovereign',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 6,
                name_ko: '벚꽃',
                category: 'sakura',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 6,
                name_ko: '적색경보',
                category: 'redalert',
                level: 0,
                cost: '배틀패스 액트2 티어35',
            },
        ]
    },
    {
        id: 6,
        name: 'Spectre',
        name_ko: '스펙터',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '프리즘',
                category: 'prism',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '아발란체',
                category: 'avalanche',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 2,
                name_ko: '럭스',
                category: 'luxe',
                level: 0,
                cost: '875 VP',
            },
            // {
            //     id: 3,
            //     name_ko: '럭스 레벨2',
            //     category: 'luxe',
            //     level: 2,
            //     cost: '875 VP',
            // },
            // {
            //     id: 4,
            //     name_ko: '럭스 레벨3',
            //     category: 'luxe',
            //     level: 3,
            //     cost: '875 VP',
            // },
            // {
            //     id: 5,
            //     name_ko: '럭스 레벨4',
            //     category: 'luxe',
            //     level: 4,
            //     cost: '875 VP',
            // },
            {
                id: 6,
                name_ko: '킹덤',
                category: 'kingdom',
                level: 0,
                cost: '배틀패스 액트1 티어5',
            },
            {
                id: 7,
                name_ko: '프라임 1',
                category: 'prime',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 8,
                name_ko: '프라임 2',
                category: 'prime',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 9,
                name_ko: '프라임 3',
                category: 'prime',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 10,
                name_ko: '프라임 4',
                category: 'prime',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 11,
                name_ko: '콘벡스',
                category: 'convex',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 12,
                name_ko: '하이브마인드',
                category: 'hivemind',
                level: 0,
                cost: '배틀패스 액트2 티어5',
            },
            {
                id: 13,
                name_ko: '스플라인 1',
                category: 'spline',
                level: 1,
                cost: '미정',
            },
            {
                id: 14,
                name_ko: '스플라인 2',
                category: 'spline',
                level: 2,
                cost: '미정',
            },
            {
                id: 15,
                name_ko: '스플라인 3',
                category: 'spline',
                level: 3,
                cost: '미정',
            },
            {
                id: 16,
                name_ko: '스플라인 4',
                category: 'spline',
                level: 4,
                cost: '미정',
            },
        ]
    },
    {
        id: 7,
        name: 'Bucky',
        name_ko: '버키',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '갤러리아',
                category: 'galleria',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 1,
                name_ko: '킹덤',
                category: 'kingdom',
                level: 0,
                cost: '배틀패스 액트1 티어1',
            },
            {
                id: 2,
                name_ko: '도깨비 1',
                category: 'oni',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 3,
                name_ko: '도깨비 2',
                category: 'oni',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 4,
                name_ko: '도깨비 3',
                category: 'oni',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 5,
                name_ko: '도깨비 4',
                category: 'oni',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 6,
                name_ko: '적색경보',
                category: 'redalert',
                level: 0,
                cost: '배틀패스 액트2 티어30',
            },
        ]
    },
    {
        id: 8,
        name: 'Judge',
        name_ko: '저지',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '럭스',
                category: 'luxe',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 1,
                name_ko: '러쉬',
                category: 'rush',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 2,
                name_ko: 'DOT EXE',
                category: 'dotexe',
                level: 0,
                cost: '배틀패스 액트1 티어40',
            },
            {
                id: 3,
                name_ko: '콘벡스',
                category: 'convex',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 4,
                name_ko: '엘더플레임 1',
                category: 'elderflame',
                level: 1,
                cost: '2475 VP',
            },
            {
                id: 5,
                name_ko: '엘더플레임 2',
                category: 'elderflame',
                level: 2,
                cost: '2475 VP',
            },
            {
                id: 6,
                name_ko: '엘더플레임 3',
                category: 'elderflame',
                level: 3,
                cost: '2475 VP',
            },
            {
                id: 7,
                name_ko: '엘더플레임 4',
                category: 'elderflame',
                level: 4,
                cost: '2475 VP',
            },
            {
                id: 8,
                name_ko: '폴리폭스',
                category: 'polyfox',
                level: 0,
                cost: '배틀패스 액트2 티어10',
            },
            {
                id: 9,
                name_ko: '글리치팝 1',
                category: 'glitchpop',
                level: 1,
                cost: '2175 VP',
            },
            {
                id: 10,
                name_ko: '글리치팝 2',
                category: 'glitchpop',
                level: 2,
                cost: '2175 VP',
            },
            {
                id: 11,
                name_ko: '글리치팝 3',
                category: 'glitchpop',
                level: 3,
                cost: '2175 VP',
            },
            {
                id: 12,
                name_ko: '글리치팝 4',
                category: 'glitchpop',
                level: 4,
                cost: '2175 VP',
            },
        ]
    },
    {
        id: 9,
        name: 'Bulldog',
        name_ko: '불독',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '무사',
                category: 'ronin',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 1,
                name_ko: '러쉬',
                category: 'rush',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 2,
                name_ko: '아리스토크랫',
                category: 'aristocrat',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 3,
                name_ko: '쿠튀르',
                category: 'couture',
                level: 0,
                cost: '배틀패스 액트1 티어10',
            },
            {
                id: 4,
                name_ko: '콘벡스',
                category: 'convex',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 5,
                name_ko: '폴리폭스',
                category: 'polyfox',
                level: 0,
                cost: '배틀패스 액트2 티어15',
            },
            {
                id: 8,
                name_ko: '글리치팝 1',
                category: 'glitchpop',
                level: 1,
                cost: '2175 VP',
            },
            {
                id: 9,
                name_ko: '글리치팝 2',
                category: 'glitchpop',
                level: 2,
                cost: '2175 VP',
            },
            {
                id: 10,
                name_ko: '글리치팝 3',
                category: 'glitchpop',
                level: 3,
                cost: '2175 VP',
            },
            {
                id: 11,
                name_ko: '글리치팝 4',
                category: 'glitchpop',
                level: 4,
                cost: '2175 VP',
            },
        ]
    },
    {
        id: 10,
        name: 'Guardian',
        name_ko: '가디언',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '갤러리아',
                category: 'galleria',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 1,
                name_ko: '프라임 1',
                category: 'prime',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 2,
                name_ko: '프라임 2',
                category: 'prime',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 3,
                name_ko: '프라임 3',
                category: 'prime',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 4,
                name_ko: '프라임 4',
                category: 'prime',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 5,
                name_ko: '소버린 1',
                category: 'sovereign',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 6,
                name_ko: '소버린 2',
                category: 'sovereign',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 7,
                name_ko: '소버린 3',
                category: 'sovereign',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 8,
                name_ko: '소버린 4',
                category: 'sovereign',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 9,
                name_ko: '도깨비 1',
                category: 'oni',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 10,
                name_ko: '도깨비 2',
                category: 'oni',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 11,
                name_ko: '도깨비 3',
                category: 'oni',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 12,
                name_ko: '도깨비 4',
                category: 'oni',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 13,
                name_ko: '폴리폭스',
                category: 'polyfox',
                level: 0,
                cost: '배틀패스 액트2 티어20',
            },
            {
                id: 14,
                name_ko: '네뷸라',
                category: 'nebula',
                level: 0,
                cost: '1775 VP',
            },
        ]
    },
    {
        id: 11,
        name: 'Phantom',
        name_ko: '팬텀',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '아발란체',
                category: 'avalanche',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '프리즘',
                category: 'prism',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 2,
                name_ko: '갤러리아',
                category: 'galleria',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 3,
                name_ko: '러쉬',
                category: 'rush',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 4,
                name_ko: '킹덤',
                category: 'kingdom',
                level: 0,
                cost: '배틀패스 액트1 티어25',
            },
            {
                id: 5,
                name_ko: '도깨비 1',
                category: 'oni',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 6,
                name_ko: '도깨비 2',
                category: 'oni',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 7,
                name_ko: '도깨비 3',
                category: 'oni',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 8,
                name_ko: '도깨비 4',
                category: 'oni',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 9,
                name_ko: '네뷸라',
                category: 'nebula',
                level: 0,
                cost: '1775 VP',
            },
            {
                id: 10,
                name_ko: '스플라인 1',
                category: 'spline',
                level: 1,
                cost: '미정',
            },
            {
                id: 11,
                name_ko: '스플라인 2',
                category: 'spline',
                level: 2,
                cost: '미정',
            },
            {
                id: 12,
                name_ko: '스플라인 3',
                category: 'spline',
                level: 3,
                cost: '미정',
            },
            {
                id: 13,
                name_ko: '스플라인 4',
                category: 'spline',
                level: 4,
                cost: '미정',
            },
        ]
    },
    {
        id: 12,
        name: 'Vandal',
        name_ko: '밴달',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '아발란체',
                category: 'avalanche',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '약탈자',
                category: 'reaver',
                level: 0,
                cost: '1775 VP',
            },
            {
                id: 2,
                name_ko: '럭스',
                category: 'luxe',
                level: 0,
                cost: '875 VP',
            },
            // {
            //     id: 3,
            //     name_ko: '럭스 레벨2',
            //     category: 'luxe',
            //     level: 2,
            //     cost: '875 VP',
            // },
            // {
            //     id: 4,
            //     name_ko: '럭스 레벨3',
            //     category: 'luxe',
            //     level: 3,
            //     cost: '875 VP',
            // },
            // {
            //     id: 5,
            //     name_ko: '럭스 레벨4',
            //     category: 'luxe',
            //     level: 4,
            //     cost: '875 VP',
            // },
            {
                id: 6,
                name_ko: '아리스토크랫',
                category: 'aristocrat',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 7,
                name_ko: 'DOT EXE',
                category: 'dotexe',
                level: 0,
                cost: '배틀패스 액트1 티어45',
            },
            {
                id: 8,
                name_ko: '프라임 1',
                category: 'prime',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 9,
                name_ko: '프라임 2',
                category: 'prime',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 10,
                name_ko: '프라임 3',
                category: 'prime',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 11,
                name_ko: '프라임 4',
                category: 'prime',
                level: 4,
                cost: '1775 VP',
            },
            {
                id: 12,
                name_ko: '엘더플레임 1',
                category: 'elderflame',
                level: 1,
                cost: '2475 VP',
            },
            {
                id: 13,
                name_ko: '엘더플레임 2',
                category: 'elderflame',
                level: 2,
                cost: '2475 VP',
            },
            {
                id: 14,
                name_ko: '엘더플레임 3',
                category: 'elderflame',
                level: 3,
                cost: '2475 VP',
            },
            {
                id: 15,
                name_ko: '엘더플레임 4',
                category: 'elderflame',
                level: 4,
                cost: '2475 VP',
            },
            {
                id: 16,
                name_ko: '벚꽃',
                category: 'sakura',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 17,
                name_ko: '하이브마인드',
                category: 'hivemind',
                level: 0,
                cost: '배틀패스 액트2 티어25',
            },
        ]
    },
    {
        id: 13,
        name: 'Marshal',
        name_ko: '마샬',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '아발란체',
                category: 'avalanche',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '갤러리아',
                category: 'galleria',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 2,
                name_ko: '쿠튀르',
                category: 'couture',
                level: 0,
                cost: '배틀패스 액트1 티어20',
            },
            {
                id: 3,
                name_ko: '소버린 1',
                category: 'sovereign',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 4,
                name_ko: '소버린 2',
                category: 'sovereign',
                level: 2,
                cost: '1775 VP',
            },
            {
                id: 5,
                name_ko: '소버린 3',
                category: 'sovereign',
                level: 3,
                cost: '1775 VP',
            },
            {
                id: 6,
                name_ko: '소버린 4',
                category: 'sovereign',
                level: 4,
                cost: '1775 VP',
            },
        ]
    },
    {
        id: 13,
        name: 'Operator',
        name_ko: '오퍼레이터',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '프리즘',
                category: 'prism',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '무사',
                category: 'ronin',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 2,
                name_ko: '럭스',
                category: 'luxe',
                level: 0,
                cost: '875 VP',
            },
            // {
            //     id: 3,
            //     name_ko: '럭스 레벨2',
            //     category: 'luxe',
            //     level: 2,
            //     cost: '875 VP',
            // },
            // {
            //     id: 4,
            //     name_ko: '럭스 레벨3',
            //     category: 'luxe',
            //     level: 3,
            //     cost: '875 VP',
            // },
            // {
            //     id: 5,
            //     name_ko: '럭스 레벨4',
            //     category: 'luxe',
            //     level: 4,
            //     cost: '875 VP',
            // },
            {
                id: 6,
                name_ko: '약탈자 레벨1',
                category: 'reaver',
                level: 1,
                cost: '1775 VP',
            },
            {
                id: 7,
                name_ko: '약탈자 레벨5',
                category: 'reaver',
                level: 5,
                cost: '1775 VP',
            },
            {
                id: 8,
                name_ko: '콘벡스',
                category: 'convex',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 9,
                name_ko: '엘더플레임 1',
                category: 'elderflame',
                level: 1,
                cost: '2475 VP',
            },
            {
                id: 10,
                name_ko: '엘더플레임 2',
                category: 'elderflame',
                level: 2,
                cost: '2475 VP',
            },
            {
                id: 11,
                name_ko: '엘더플레임 3',
                category: 'elderflame',
                level: 3,
                cost: '2475 VP',
            },
            {
                id: 12,
                name_ko: '엘더플레임 4',
                category: 'elderflame',
                level: 4,
                cost: '2475 VP',
            },
            {
                id: 13,
                name_ko: '적색경보',
                category: 'redalert',
                level: 0,
                cost: '배틀패스 액트2 티어45',
            },
            {
                id: 14,
                name_ko: '스플라인 1',
                category: 'spline',
                level: 1,
                cost: '미정',
            },
            {
                id: 15,
                name_ko: '스플라인 2',
                category: 'spline',
                level: 2,
                cost: '미정',
            },
            {
                id: 16,
                name_ko: '스플라인 3',
                category: 'spline',
                level: 3,
                cost: '미정',
            },
            {
                id: 17,
                name_ko: '스플라인 4',
                category: 'spline',
                level: 4,
                cost: '미정',
            },
        ]
    },
    {
        id: 14,
        name: 'Ares',
        name_ko: '아레스',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '프리즘',
                category: 'prism',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 1,
                name_ko: '아리스토크랫',
                category: 'aristocrat',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 2,
                name_ko: '러쉬',
                category: 'rush',
                level: 0,
                cost: '875 VP',
            },
            {
                id: 3,
                name_ko: '벚꽃',
                category: 'sakura',
                level: 0,
                cost: '1275 VP',
            },
            {
                id: 4,
                name_ko: '하이브마인드',
                category: 'hivemind',
                level: 0,
                cost: '배틀패스 액트2 티어1',
            },
            {
                id: 5,
                name_ko: '네뷸라',
                category: 'nebula',
                level: 0,
                cost: '1775 VP',
            },
        ]
    },
    {
        id: 15,
        name: 'Odin',
        name_ko: '오딘',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: 'DOT EXE',
                category: 'dotexe',
                level: 0,
                cost: '배틀패스 액트1 티어30',
            },
            {
                id: 1,
                name_ko: '글리치팝 1',
                category: 'glitchpop',
                level: 1,
                cost: '2175 VP',
            },
            {
                id: 2,
                name_ko: '글리치팝 2',
                category: 'glitchpop',
                level: 2,
                cost: '2175 VP',
            },
            {
                id: 3,
                name_ko: '글리치팝 3',
                category: 'glitchpop',
                level: 3,
                cost: '2175 VP',
            },
            {
                id: 4,
                name_ko: '글리치팝 4',
                category: 'glitchpop',
                level: 4,
                cost: '2175 VP',
            },
        ]
    },
    {
        id: 16,
        name: 'Knife',
        name_ko: '전술용 나이프',
        skins: [
            {
                id: -1,
                name_ko: '기본 스킨',
                category: 'normal',
                level: 0,
                cost: ''
            },
            {
                id: 0,
                name_ko: '프리즘',
                category: 'prism',
                level: 0,
                cost: '2550 VP',
            },
            {
                id: 1,
                name_ko: '약탈자',
                category: 'reaver',
                level: 0,
                cost: '3550 VP',
            },
            {
                id: 2,
                name_ko: '럭스',
                category: 'luxe',
                level: 0,
                cost: '1750 VP',
            },
            {
                id: 3,
                name_ko: '임페리엄',
                category: 'imperium',
                level: 0,
                cost: '2550 VP',
            },
            {
                id: 4,
                name_ko: '킹덤',
                category: 'kingdom',
                level: 0,
                cost: '배틀패스 액트1 티어50',
            },
            {
                id: 5,
                name_ko: '프라임',
                category: 'prime',
                level: 0,
                cost: '3550 VP',
            },
            {
                id: 6,
                name_ko: '소버린',
                category: 'sovereign',
                level: 0,
                cost: '3550 VP',
            },
            {
                id: 7,
                name_ko: '엘더플레임',
                category: 'elderflame',
                level: 0,
                cost: '4950 VP',
            },
            {
                id: 8,
                name_ko: '도깨비',
                category: 'oni',
                level: 0,
                cost: '3550 VP',
            },
            {
                id: 9,
                name_ko: '하이브마인드',
                category: 'hivemind',
                level: 0,
                cost: '배틀패스 액트2 티어50',
            },
            {
                id: 10,
                name_ko: '글리치팝',
                category: 'glitchpop',
                level: 0,
                cost: '4350 VP',
            },
            {
                id: 11,
                name_ko: '네뷸라',
                category: 'nebula',
                level: 0,
                cost: '3550 VP',
            },
            {
                id: 12,
                name_ko: '스플라인',
                category: 'spline',
                level: 0,
                cost: '미정',
            },
        ]
    },
]

export const skinCollection = [
    {
        id: 0,
        name: 'Luxe',
        name_ko: '럭스',
        image: `${staticServer}/weaponskins/luxe-skins-collection.png`
    },
    {
        id: 1,
        name: 'Prism',
        name_ko: '프리즘',
        image: `${staticServer}/weaponskins/prism-skins-collection.png`
    },
    {
        id: 2,
        name: 'Reaver',
        name_ko: '약탈자',
        image: `${staticServer}/weaponskins/reaver-skins-collection.png`
    },
    {
        id: 3,
        name: 'Prime',
        name_ko: '프라임',
        image: `${staticServer}/weaponskins/hypebeast-skins-collection.png`
    },
]